name: flutter_bluetooth_classic_serial
description: A Flutter plugin for Bluetooth Classic communication on Android, iOS, and Windows platforms. Supports device discovery, connection management, and data transmission.
version: 1.0.1
homepage: https://github.com/C0DE-IN/flutter_bluetooth_classic
repository: https://github.com/C0DE-IN/flutter_bluetooth_classic.git
issue_tracker: https://github.com/C0DE-IN/flutter_bluetooth_classic/issues
documentation: https://github.com/C0DE-IN/flutter_bluetooth_classic/blob/main/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_bluetooth_classic
        pluginClass: FlutterBluetoothClassicPlugin
      ios:
        pluginClass: FlutterBluetoothClassicPlugin
      windows:
        pluginClass: FlutterBluetoothClassicPlugin
        fileName: flutter_bluetooth_classic_plugin.cpp

topics:
  - bluetooth
  - bluetooth-classic
  - communication
  - serial
  - connectivity
