name: flutter_bluetooth_classic
description: A Flutter plugin for Bluetooth Classic communication supporting both Android and iOS platforms.
version: 1.0.0
homepage: https://github.com/yourusername/flutter_bluetooth_classic

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_bluetooth_classic
        pluginClass: FlutterBluetoothClassicPlugin
      ios:
        pluginClass: FlutterBluetoothClassicPlugin
